function parsave(fname, cLL_bip_off, cLL_bip_on, cLL_nvc_off, cLL_nvc_on, ...
        cLL_tot_off, cLL_tot_on, P_nvc_off, P_nvc_on, P_bip_off, ...
        P_bip_on, P_tot_off, P_tot_on, P_coh_off, P_coh_on, ...
        P_vc_off, P_vc_on, P_EMG_off, P_EMG_on, type, Nex, ...
        cLE_bip_off, cLE_bip_on, cLE_tot_off, cLE_tot_on, f, ...
        P_inc_off, P_inc_on, Patient, LFPact, w0, scale, ...
        tsmo, usenan, dec, rigor)
    
save(fname, 'cLL_bip_off', 'cLL_bip_on', 'cLL_nvc_off', 'cLL_nvc_on', ...
        'cLL_tot_off', 'cLL_tot_on', 'P_nvc_off', 'P_nvc_on', 'P_bip_off', ...
        'P_bip_on', 'P_tot_off', 'P_tot_on', 'P_coh_off', 'P_coh_on', ...
        'P_vc_off', 'P_vc_on', 'P_EMG_off', 'P_EMG_on', 'type', 'Nex', ...
        'cLE_bip_off', 'cLE_bip_on', 'cLE_tot_off', 'cLE_tot_on', 'f', ...
        'P_inc_off', 'P_inc_on', 'Patient', 'LFPact', 'w0', 'scale', ...
        'tsmo', 'usenan', 'dec', 'rigor')
    
end